language: php
sudo: required
dist: trusty
group: edge
php:
    - 5.6

services:
    - mysql

before_script:
    - composer install
install:
    - cp app/config/parameters.yml.travis app/config/parameters.yml
    - php app/console doctrine:database:create
    - php app/console doctrine:schema:create
    - php app/console doctrine:fixtures:load

script:
    - phpunit -c app

notifications:
    email:
        -  psynowiec@gmail.com