language: php
sudo: required
dist: trusty
group: edge
php:
    - 5.6

services:
    - mysql

before_script:
    - composer install
    - cp app/config/parameters.yml.travis app/config/parameters.yml
    - ./app/console doctrine:database:create --env=test
    - ./app/console doctrine:schema:create --env=test
    - ./app/console doctrine:fixtures:load -n --env=test

script:
    - phpunit -c app

notifications:
    email:
        -  psynowiec@gmail.com