<?php

namespace mysiar\Bundle\InvoiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function getAllClientsForUser( $user ){
        return $this->_em->getRepository($this->_entityName)
            ->findBy(
                array( 'invoiceUser' => $user),
                array( 'companyName' => 'ASC')
            );

    }


    /**
     * Gets client by its id from repository
     *
     * @param $id
     * @return object
     */
    public function getClientById( $id )
    {
        return $this->_em->find($this->_entityName, $id);
    }

    /**
     * Checks if client is own by logged user
     *
     * @param Client $client
     * @param InvoiceUser $user
     * @return bool
     */
    public function clientOwner( $client, $user )
    {
        return $user == $client->getInvoiceUser() ? true : false;
    }
}
