<?php

namespace mysiar\Bundle\InvoiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function getAllClientsForUser( $user ){
        return $this->_em->getRepository($this->_entityName)
            ->findBy(
                array( 'invoiceUser' => $user),
                array( 'companyName' => 'ASC')
            );

    }
}
