<?php

namespace mysiar\Bundle\InvoiceBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FOS\UserBundle\FOSUserBundle;
use mysiar\Bundle\InvoiceBundle\Entity\IUser;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;


/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends EntityRepository
{

    /**
     * Gets invoice by its id from repository
     *
     * @param $id
     * @return object
     */
    public function getInvoiceById( $id )
    {
        return $this->_em->find($this->_entityName, $id);
    }

   /**
     * Checks if invoice is own by logged user
     *
     * @param Invoice $invoice
     * @param IUser $user
     * @return bool
     */
    public function invoiceOwner( $invoice, $user )
    {
        return $user == $invoice->getIuser() ? true : false;
    }

    public function getAllInvoiceForUser( $user ){
        return $this->_em->getRepository($this->_entityName)->findBy(array( 'iuser' => $user));
    }

}
