<?php

namespace mysiar\Bundle\InvoiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceElementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceElementsRepository extends EntityRepository
{
}
