<?php

namespace mysiar\Bundle\InvoiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceElementRepository extends EntityRepository
{
}
