<?php

namespace mysiar\Bundle\InvoiceBundle\Repository;

/**
 * InvoiceUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceUserRepository extends \Doctrine\ORM\EntityRepository
{
}
