<?php

namespace mysiar\Bundle\InvoiceBundle\Repository;

/**
 * IUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IUserRepository extends \Doctrine\ORM\EntityRepository
{
}
